### ISSUE TITLE
Using values from within the record

### ISSUE THREAD

**Issue by geek876** [k24d/fluent-plugin-splunkapi#5]
Would it be possible to set `sourcetype` and `host` values using  existing values within the record ?  
We have forwarding setup such that client -> fluentd-server (forwarder) -> Splunk. Due to this, the `host` value within splunk for any record is alway of the `fluentd-server`. For a sample record
``` 
2016-07-14 16:30:01 +0100: {"source":"app-2","daemon":"CRON","pid":"21212","message":"(root) CMD (/var/awslogs/bin/awslogs-nanny.sh > /dev/null 2>&1)","service":"syslog","log":"syslog","hostname":"app-2","channel":"text","environment":"env1"}

```
I tried setting 

```
<match>
type splunkapi
protocol rest
server splunk-1
verify false
auth x:x
sourcetype {channel}
host {source}
</match>
```
But it fails.

**Comment by k24d** [comment]
Unfortunately it's not possible at this moment and it's not easily done because we have to build separate Splunk API calls for each combination of "host", "source", and "sourcetype".  We have to build separate buffers for each combination.

Instead of trying to modify this plugin, you could try some fluentd filter plugins.  There was at least one plugin that generates plugin configuration dynamically like this:

https://github.com/tagomoris/fluent-plugin-forest

I'm not sure if it works with the latest Fluentd.  Fluentd recently reimplemented filter architecture, and I'm not familiar with that.

**Comment by geek876** [comment]
@k24d Thanks but the `fluent-plugin-forest` won't help us as we don't have that information in the tag. If I understand it correctly, `fluent-plugin-forest` can create dynamic configs based on tags.

**Comment by k24d** [comment]
it seems Splunk has implemented a new feature called "HTTP Event Collector", which looks much better than the traditional API I used in this plugin.

http://dev.splunk.com/view/event-collector/SP-CAAAE6P
